# first time use notebook

## importing dataset using pandas

In [3]:
# pandas
import pandas as pd
df = pd.read_csv('final.csv') # read csv is a function in pandas and df is a varibale used to store it

,Unnamed: 0,STATE/UT,YEAR,POPULATION,MALES,FEMALES,MALES(per_100k),FEMALES(per_100k),TOTAL IPC CRIMES,TOTAL IPC CRIMES(per_100k),...,RAPE,RAPE(per_100k),RIOTS,RIOTS(per_100k),ROBBERY,ROBBERY(per_100k),THEFT,THEFT(per_100k),OTHER IPC CRIMES,OTHER IPC CRIMES(per_100k)
0,0,A&N Islands,2001,356,193,163,54213.483146,45786.516854,1316,369662.921348,...,6,1685.393258,26,7303.370787,8,2247.191011,130,36516.853933,646,181460.674157
1,1,Andhra Pradesh,2001,76210,38527,37683,50553.733106,49446.266894,260178,341396.142239,...,1742,2285.789267,6002,7875.606876,1258,1650.702008,33502,43960.110222,68688,90129.904212
2,2,Arunachal Pradesh,2001,1098,580,518,52823.315118,47176.684882,4684,426593.806922,...,66,6010.928962,48,4371.584699,168,15300.546448,886,80692.167577,1236,112568.306011
3,3,Assam,2001,26656,13777,12878,51684.423770,48311.824730,73754,276688.175270,...,1634,6129.951981,5906,22156.362545,1374,5154.561825,10734,40268.607443,18630,69890.456182
4,4,Bihar,2001,82999,43244,39755,52101.832552,47898.167448,176864,213091.723997,...,1776,2139.784817,17212,20737.599248,4406,5308.497693,19402,23376.185255,73334,88355.281389
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
463,463,Tamil Nadu,2013,68265,34248,34017,50169.193584,49830.806416,407158,596437.413023,...,1846,2704.167582,5402,7913.279133,4372,6404.453234,23900,35010.620376,255700,374569.691643
464,464,Tripura,2013,3700,1893,1807,51162.162162,48837.837838,12420,335675.675676,...,466,12594.594595,246,6648.648649,88,2378.378378,1066,28810.810811,3156,85297.297297
465,465,Uttar Pradesh,2013,207739,109466,98273,52694.005459,47305.994541,452890,218009.136465,...,6100,2936.376896,12178,5862.163580,7182,3457.222765,83898,40386.253905,160490,77255.594761
466,466,Uttarakhand,2013,10224,5217,5006,51026.995305,48963.223787,19092,186737.089202,...,456,4460.093897,668,6533.646322,276,2699.530516,3192,31220.657277,4714,46107.198748
467,467,West Bengal,2013,91122,46836,44287,51399.223020,48601.874410,339070,372105.528851,...,3370,3698.338491,12284,13480.827901,1294,1420.074186,45808,50271.065165,141476,155259.981124